wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.15.8
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1691792284.362288
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 23
      4: 3.11.4
      5: 0.15.8
      8:
      - 1
      - 5
